### ISSUE TITLE
Death to Merkle Tree

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2192]
Problem:
- Merkle proof verification costs about 35k gas on the destination chain
- Relayers need to be indexing in order to relay messages which can take some startup time and require heavy RPC load
- explorer would also need to access the merkle tree for self-relaying

Requirements:
- Have a signature scheme that does not require merkle proofs on the destination chain in the optimistic case (while still allow for them for censorship resistance)
- A new MultisigISM type that verifies using this signature scheme
- Validators should continue to be able to sign right away without the need to block on indexing
- Relayers should be able to relay without needing to index and build the merkle tree

Stakeholders:
- Validators
  - Validators now need to also index which will require persistent storage and increased RPC load
  - Should be able to upgrade at their own leisure
- Relayers
  - Should be able to relay messages for both signature schemes/ism types

User flows: 
- N/A

Out of scope:
- Self-relaying in the explorer

Work:

```[tasklist]
### 1. Implement smart contract changes and roll them out
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2173 
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2191
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2291
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2340
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2292
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2223
```

```[tasklist]
### 2. Implement Aggregation ISM for the default ISM eventually
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1757
```

```[tasklist]
### 3. Deploy aggregation of MessageIDISM and MerkleISM as default
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2430
- [ ] #2224
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2477
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2478
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2479
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2596
```

```[tasklist]
### Update hyperlane-deploy
- [ ] Implement TS deployers to deploy the aggregation in infra/hyperlane-deploy
- [ ] #2320
- [ ] Add a draft title or issue reference here
```

Can be done independently over time: 

- [x] #2250
