### ISSUE TITLE
Streamline config shapes (rust)

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2215]
This is the sister ticket to #2214 . It streamlines the existing chain config with the typescript one as they are so close to each other already. In addition to that streamlining benefit, it also captures the following benefits:

- It would specify a default RPC for the agent config (similar to SDK-specified default RPCs in `ChainMetadata`), which would potentially reduce one more argument to need to be specified via ENV vars to get started
- It moves the `rpcConsensusType` apart from `connection` and makes it easier to specify different defaults per agent type (i.e. fallback for relayer and scraper, quorum for validator) and thus obsoletes https://github.com/hyperlane-xyz/issues/issues/438
```[tasklist]
### Subissues
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/532
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2662
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2663
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2702
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2701
```

```[tasklist]
### Tasks
- [x] Update in accordance to spec https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2203/files#diff-0dda34e51b45fcb259676791b216443495e465f6ec7c372fc77ec9abe9b8409aR90
- [x] Split rpc consensus type from connection details
- [x] Update typescript agent definitons
- [x] Update Rust config definitions and parsing for base agent config
- [x] Update Rust config definitions and parsing for each individual agents config
- [x] Write up/propose rollout plan and decide on one
- [x] Update deployment config output
- [x] Update Helm and deploy tooling
- [x] Cleanup old typescript agent config defintions
- [x] Update e2e tests to use new configs
- [x] Verify generated deployment configs are correct
```
```[tasklist]
### PRs
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2658
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2665
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2666
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2687
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2659
```

**Comment by mattiecnvr** [comment]
Relates to #1865

**Comment by mattiecnvr** [comment]
Draft PR to track progress
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2659

**Comment by mattiecnvr** [comment]
High-level rollout plan proposals:

1) Support only the new config with the next agent release which would allow us to delete a bunch of dead code now rather than having to do it later and reduces the surface area for bugs
2) Support both configs by attempting to first parse it as a new config and then parse it as the old config format and create an issue to cleanup deprecated code in the future. Main risk here is that it might make the errors hard to understand if we are not careful.
3) Support both configs using a flag to indicate the which config should be read. This would allow us silently roll out the changes internally and eventually cut over by changing the default to the new config format. Downside is it means defining a new flag either as env or arg and it also still has the deprecated code hanging around.
4) Something else?

(1) is the easiest but (3) is pretty easy. (2) might be finicky.

**Comment by mattiecnvr** [comment]
This will be kept up to date with main, and then after v3 is merged, we will go ahead and merge this in before we release.

**Comment by avious00** [comment]
@tkporter to review helm charts portion, dan has done his review

**Comment by nambrot** [comment]
@mattiecnvr is #2659 the PR that we will merge into v3?
