### ISSUE TITLE
Epic: Hyperlane implementations for Cosmos

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2421]
This epic captures the work that goes towards supporting Hyperlane implementations for cosmos chains. There are currently two distinct implementations in the works, one that implements Hyperlane wholly as a cosmos-sdk module and one via cosmwasm.

## Cosmos-SDK Module

Strangelove has broken up the [Cosmos SDK Hyperlane implementation into 3 modules](https://github.com/strangelove-ventures/hyperlane-cosmos/tree/main/x):

1. mailbox (merkle tree state commitments, dispatch/process interfaces, default ISM config)
2. interchain security module (implements standard multisig types)
3. interchain gas paymaster (**not started**)

They have a local chain test setup where they are dispatching and processing messages against a configured default ISM of local signers which [we is reproducible](https://github.com/strangelove-ventures/hyperlane-cosmos/tree/main#running-interchain-tests)

See [otter transcript from architecture overview meeting](https://otter.ai/u/rzCW3h-iwOOaK1HMuf2ItaiPRFk?utm_source=copy_url) and [google drive meeting recording](https://drive.google.com/file/d/1zJfDmq1FJFRfXOIn6vtJZIugehIPT5ua/view?usp=sharing)

These task lists below capture the outstanding work:

```[tasklist]
### Protocol MVP Feature Completion
- [x] Mailbox Module
- [x] ISM Module with multisig metadata verification
- [ ] IGP Module
```

```[tasklist]
### Usage Demo and Testing
- [x] Develop a CosmWasm library to initiate and receive a Hyperlane message transfer
- [ ] Sho
```

```[tasklist]
### Agents Work
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2422
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2486
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2419
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2423
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2424
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2552
- [ ] Test validators running against cosmos mailbox
- [ ] Test relayers running against cosmos mailbox
```

## Cosmwasm

This implementation is being worked on in https://github.com/many-things/cw-hyperlane

```[tasklist]
### CosmWasm contracts
- [ ] Add high level tasks here (and who does them)
```

```[tasklist]
### Agent integration (might have overlap with Cosmos-sdk module agent work
- [ ] Add high level tasks here (and who does them)
```

**Comment by nambrot** [comment]
@yorhodes How will the indexing for the main agents (validator/relayer), but also scraper work?

**Comment by yorhodes** [comment]
> @yorhodes How will the indexing for the main agents (validator/relayer), but also scraper work?

not totally sure how indexing usually works in cosmos
suggest implementers follow the (new) implementation guide
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2552
