### ISSUE TITLE
Sealevel: audit remediation [informational] 

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#2604]
based on sec3 audit. low priority issues were addressed in [#2544](https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2544). these are in the backlog
```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2592
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2593
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2595
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2594
```
