### ISSUE TITLE
Assess new CLI as primary getting started path

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#2614]
Review CLI 

```[tasklist]
### Tasks
- [x] Confirm with Rossy CLI is ready to test
- [ ] Dogfood new CLI
- [ ] Find DX pain points in CLI and provide feedback to Rossy
- [ ] Identify feature parity gaps between hyperlane-deploy and CLI
- [ ] Decide if CLI can replace hyperlane-deploy
```

**Comment by aroralanuk** [comment]
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2573#issuecomment-1716253560
