### ISSUE TITLE
Agents are resilient to merkle tree double insertion

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#2720]
Related to https://github.com/hyperlane-xyz/issues/issues/561

relayer merkle builder assumes message nonce implies tree index
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/16146f0f03d0b0be67583cf16b22a3c50abdd977/rust/agents/relayer/src/merkle_tree_builder.rs#L118-L119

validator checkpoint submitter assumes message nonce implies tree index
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/16146f0f03d0b0be67583cf16b22a3c50abdd977/rust/agents/validator/src/submit.rs#L85-L89
```[tasklist]
### Tasks
- [x] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2739
- [x] create a new agent indexer for this event - Kunal (pr incoming today 9/18)
- [x] modify agent merkle tree builder to be independent of message indexing - Daniel & Trevor
- [x] modify relayer to spawn new indexer and remove merkle tree logic from main processor/submitter loops  - Daniel & Trevor
```

**Comment by daniel-savu** [comment]
Relatively quick braindump based on the whiteboarding session below.

**DTM indexing**
- completion criteria:
	- use merkle tree hook as both the required and custom hook (2 insertions)
	- do not use the merkle tree hook at all (0 insertions)
- spawn new merkle builder task that iterates hyperlane DB
	- can do forward cursor indexing for relayer
	- for validator, might need different logic depending on the tip at startup (forward - forward indexing?). Look into validator indexing logic
- remove merkle builder Arc from Processor task, pass it to the merkle tree builder task instead
- Move merkle tree-building logic from message processor task, to merkle tree builder task
- add retrying logic for fetching insertions
- return Ok(None) to trigger retries in the builder, if the merkle tree is not yet available
- mapping between message id and nonce; should drop all usage of message nonce and use the leaf count instead; could store in memory or in storage
	- replace `retrieve_message_by_nonce` with `retrieve_leaf_by_index`, where index a u32

**Comment by daniel-savu** [comment]
finished in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2815
