### ISSUE TITLE
Epic: Hyperlane CLI & Registry

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2801]
Solving registry unblocks partner https://github.com/hyperlane-xyz/issues/issues/808 + https://github.com/hyperlane-xyz/issues/issues/797 integrations

```[tasklist]
### Replace hyperlane-deploy but without new registry
- [ ] https://github.com/hyperlane-xyz/issues/issues/530
```

```[tasklist]
### Infra parity
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2797
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2798
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2799
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2800
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2802
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2803
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2804
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2808
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2809
```

```[tasklist]
### Supporting PI with new registry
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2810
```
```[tasklist]
### Older Related Issues
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2178
- [ ] https://github.com/hyperlane-xyz/issues/issues/451
- [ ] https://github.com/hyperlane-xyz/issues/issues/461
```

```[tasklist]
### Other Registries
- [ ] Relayer Registry
- [ ] Validator Registry
- [ ] ISM Registry
```

see succinct [deployment registry](https://alpha.succinct.xyz/succinctlabs/telepathyx/deployments) for inspo

```[tasklist]
### Other registry tickets
- [ ] https://github.com/hyperlane-xyz/issues/issues/451
- [ ] https://github.com/hyperlane-xyz/issues/issues/461
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2440
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2178
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2198
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2579
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2476
```

**Comment by nambrot** [comment]
@tkporter how does this relate to #3503, is this going to be mostly the backlog epic kind of?

**Comment by avious00** [comment]
> [@tkporter](https://github.com/tkporter) how does this relate to [#3503](https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3503), is this going to be mostly the backlog epic kind of?

this is the old one that i believe will be mostly closed/merged by @tkporter

**Comment by avious00** [comment]
@tkporter i closed all of the tickets from here from october fyi as well as this epic
