### ISSUE TITLE
Epic: Migration from Infra

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#3317]
```[tasklist]
### Configuration
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3135
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3064
```

```[tasklist]
### Artifacts
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3328
```

**Comment by avious00** [comment]
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3326 may also be relevant here

**Comment by nambrot** [comment]
Seems like at this point this is a dupe of https://github.com/hyperlane-xyz/issues/issues/1169 ? @tkporter
