### ISSUE TITLE
Epic: Multi-Collateral Warp Routes

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#3342]
Warp routes typically are only collateralized on a single chain. However, for assets like ETH or USDC, folks might want warp routes that can be deposited to from multiple chains, especially rollups. 

From a contract perspective that is mostly supported already. Warp route configuration and the Warp UI might not have full support

```[tasklist]
### Basic support
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3639
- [x] Support in Warp UI via WarpCore
```

In this basic level of support, users may not get to redeem collateral on the chain of their choice. For that, rebalancing is necessary.

```[tasklist]
### Rebalancing improvements
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2196
- [ ] Include MEV incentive fee for bridging from a certain direction
```
