### ISSUE TITLE
Epic: `v3` cleanup

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#3352]
```[tasklist]
### Docs
- [ ] https://github.com/hyperlane-xyz/issues/issues/696
```

```[tasklist]
### More Decentralization
- [ ] https://github.com/hyperlane-xyz/issues/issues/673
- [ ] https://github.com/hyperlane-xyz/issues/issues/813
```

```[tasklist]
### More Security
- [ ] Code4rena challenge after ICA and more hooks shipped
- [ ] Change Immunefi bounty from v2 to v3
- [ ] https://github.com/hyperlane-xyz/issues/issues/1007
```

```[tasklist]
### Application Parity
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3197
- [ ] https://github.com/hyperlane-xyz/issues/issues/540
- [ ] https://github.com/hyperlane-xyz/issues/issues/578
```

```[tasklist]
### Tech Debt
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2898
```

```[tasklist]
### Test Coverage
- [ ] https://github.com/hyperlane-xyz/issues/issues/657
- [ ] https://github.com/hyperlane-xyz/issues/issues/703
```
