### ISSUE TITLE
Epic: improve scraper & scraper operations

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3357]
Improvements to the scraper codebase & the operational practices around it. Some of these came out of [this comment](https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3329#issuecomment-1971012488).

In rough order of priority high -> low

```[tasklist]
### Scraper operations improvements
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3324
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3333
```

```[tasklist]
### Scraper improvements
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3121
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3335
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3334
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3331
```
