### ISSUE TITLE
Epic: longer term better indexing positioning

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3414]
**Follows https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3281, which is intended to be done ASAP**

We should do these next - these are also in chronological order. These are less pressing but after this we'll be in a good indexing situation where we can use alternative modalities and can spin up a relayer that delivers messages without it having indexed all historical data.

```[tasklist]
### Better indexing positioning
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3265
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3266
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3365
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3268
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3336
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3269
```
