### ISSUE TITLE
Epic: Add yield-bearing warp routes to token deployer

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#3416]
## Problem

Yield bearing warp routes are implemented but are not supported in our token deployer.

## Solution

Add a new [token type](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/b14f997810ebd7dbdff2ac6622a149ae77010ae3/typescript/sdk/src/token/config.ts#L5) and implement support in the token deployer.

## Criteria
- [x] Support through `warp deploy` CLI command
- [x] Nice to have: Support interactive config in the `warp config` CLI command
- [x] Update docs at the bottom of Deploy Warp Route section

**Comment by avious00** [comment]
- chat with @aroralanuk or @jmrossy on changesets for PR
- and then once docs are to ready review, ping @avious00 for review + i'll coordinate with @jmrossy on CLI release

**Comment by jmrossy** [comment]
Sent Lee some info RE changesets

**Comment by ltyu** [comment]
Docs updated here https://github.com/hyperlane-xyz/v3-docs/pull/71
