### ISSUE TITLE
Epic: basic self relaying via the CLI / explorer / warp UI

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3448]
**High level outcomes**
- Only MessageIdMultisig ISMs, Routing ISMs, Aggregation ISMs, and Null ISM for now
- Able to self relay using the warp route UI, explorer, and CLI
- Everything is built in a protocol-agnostic manner, but we just implement the "view calls" etc that are involved for EVM for now

**Motivation:**
- We often just use combinations of aggregation, routing, and multisig ISMs
- We just focus on the MessageIdMultisig ISM type, as creating a merkle proof for a MerkleRootMultisig is heavyweight and atm only reasonable to do in the relayer. As it stands now, it would likely require indexing all messages, which is unreasonable to do in the CLI or explorer
- We want to lower the time to success in testing that e.g. a warp route works
- Allowing self-relaying if the relayer is having issues is a nice option for users
- We're not going with a shared WASM implementation between Rust and Typescript for a few reasons:
  - The way the agents are written, the metadata builder logic includes some very agent-specific things, e.g. a connection to the DB, metrics, a merkle tree, etc https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/rust/agents/relayer/src/msg/metadata/base.rs#L272-L282
  - Rewriting this on the Rust side would be high effort and contention for agent eng resources is high
  - Metadata building isn't likely to change so duplicating logic between Rust and Typescript so we're unlikely to have any issues with them being inconsistent due to changes in the future

See [Notion](https://www.notion.so/hyperlanexyz/Self-relaying-015f388dfff940fdb228d55cfb23a7f4) for the full thought process around this

```[tasklist]
### OPTIONAL & dependent on prioritization
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3507
```

```[tasklist]
### Metadata building in the SDK
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3449
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3450
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3451
```

```[tasklist]
### Self-delivery of messages
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3452
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3453
- [ ] https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/issues/399
```

**Comment by avious00** [comment]
hey @tkporter can you merge https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2213 into this :)

**Comment by avious00** [comment]
this is will be helpful for developers to get up and running quickly and validate a testnet deployment

**Comment by tkporter** [comment]
> hey @tkporter can you merge #2213 into this :)

sounds good, imo this epic is just a successor of that issue and there isn't anything else to roll in
