### ISSUE TITLE
Epic: agent metrics improvements

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3461]
```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3354
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3239
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3455
```
