### ISSUE TITLE
Epic: Permissionless Registry MVP

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#3503]
### Problem
1. We currently have the [hyperlane-registry](https://github.com/hyperlane-xyz/hyperlane-registry/tree/main/chains) repo which tracks `core` deployments
2. We want a way for the community to permissionlessly share and discover deployments
3. Ideally, we want both the contract artifacts and agent config of the deployments shared here (with a view that these will eventually merge) 

### Solution
- Via the CLI, developers `git clone` the registry locally and after they deploy they can choose to opt-in to the registry
- They do this by submitting a PR with the artifacts file to the local registry, which in turns submits a git diff to the `hyperlane-registry` for review
- Should include https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2809 for agents configs and the ability to run agents on behalf of a submitted deployment
- Includes mainnet and testnet deployments
- Initial work step includes https://github.com/hyperlane-xyz/issues/issues/917

#### Add'l Context
- See the older Registry epic from Oct 2023 https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2801 - this should be merged/cleaned up after this epic is created
- We want a backlog registry epic that captures end-state vision beyond this MVP, creating a registry API as opposed to cloning + creating PRs
- Check out [Succinct's deployment registry](https://alpha.succinct.xyz/succinctlabs/telepathyx/deployments) for a great live example
- Testnet deployments should be a schelling point for developers to coordinate one mailbox per chain as opposed to fragmented deployments
- Docs should be included in this epic, and for different onboarding paths w/varying degrees of infra support
```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/issues/issues/917
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2810
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2178
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3655
- [ ] https://github.com/hyperlane-xyz/v3-docs/issues/95
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3692
- [ ] https://github.com/hyperlane-xyz/hyperlane-registry/issues/42
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2476
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3581
```

**Comment by avious00** [comment]
hey @yorhodes @tkporter @nambrot @jmrossy just a heads up this is yorke's registry epic - feel free to pull issues in here. yorke to lead fleshing this out

**Comment by avious00** [comment]
start with https://github.com/hyperlane-xyz/issues/issues/917

**Comment by jmrossy** [comment]
MVP is done, all linked tasks here complete. Closing epic
