### ISSUE TITLE
Epic: Permissionless CLI for Hooks/ISMs

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#3504]
### Context 
This is the CLI counterpart to the SDK epics @yorhodes is creating, starting with https://github.com/hyperlane-xyz/issues/issues/1150 for hooks/ISMs

### Solution
```[tasklist]
### Tasks
- [ ] hyperlane hook read
- [ ] hyperlane hook apply
- [ ] hyperlane ism read
- [ ] hyperlane ism apply 
```
^ @tkporter to break down above todo's into issues and link to relevant SDK issue pair

#### Notes
- Assuming as core + warp SDK epics are created there will be CLI followup epics too
- @yorhodes mentioned for you @tkporter that there could be more tooling to move out of infra into CLI, e.g. agent health, setting exchange rates - please add to here or add'l epic

**Comment by nambrot** [comment]
@tkporter is the migration supposed to happen later or part of this epic? If that is the case, can we capture documentation and testing tickets to reflect the need before rolling this out?

**Comment by avious00** [comment]
@tkporter are the open questions still relevant?
