### ISSUE TITLE
Epic: Abacus Works IGP management

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#3567]
Goals:
- In line with the approach we take with the rest of our contracts that we manage, we will continue to use infra as our home for generating complex configs
- We will first get to a stage where IGP tooling is safe
- Then we'll make improvements to our tooling for choosing what values to quote

Blocked by some tasks related to https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3504:
* need to consider how we can get this to work with the new IGP artifact management
* need to consider how configs from this can eventually get plugged into the CLI / what format is expected

```[tasklist]
### IGP gas oracle tooling works and is safe
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3484
- [ ] https://github.com/hyperlane-xyz/issues/issues/1178
- [ ] https://github.com/hyperlane-xyz/issues/issues/1180
```

```[tasklist]
### Better quoting abilities
- [ ] https://github.com/hyperlane-xyz/issues/issues/1206
- [ ] https://github.com/hyperlane-xyz/issues/issues/1204
```
```[tasklist]
### Claiming from IGP
- [ ] https://github.com/hyperlane-xyz/issues/issues/1198
```
