### ISSUE TITLE
Epic: Overhaul (CRUD) Hook and ISM management

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#3568]
The goal of this epic is to merge the behavior from deployers, checkers, and governors into a single abstraction

```[tasklist]
### Create
- [ ] https://github.com/hyperlane-xyz/issues/issues/1153
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3575
- [ ] https://github.com/hyperlane-xyz/issues/issues/1152
```

```[tasklist]
### Read
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3129
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3436
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3578
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3579
```

```[tasklist]
### Update
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3577
- [ ] https://github.com/hyperlane-xyz/issues/issues/1156
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3839
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3695
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3750
```
```[tasklist]
### Crud Module Interface
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3574
```

```[tasklist]
### Document
- [x] Update docs to reflect changes
- [ ] https://github.com/hyperlane-xyz/v3-docs/issues/86
```
