### ISSUE TITLE
Epic: Hyperlane AVS

### ISSUE THREAD

**Issue by aroralanuk** [hyperlane-xyz/hyperlane-monorepo#3588]
We'll be implementing an Eigenlayer AVS to allow for restaked economic security for any-to-any message passing between hyperlane deployments. This epic encompasses the first milestone which includes the following:

**Step 1**: AVS contracts like HyperlaneServiceManager, IRemoteChallenger, etc with a comprehensive test suite.
**Step 2**: Changes in the relayer to post their ECDSA signature for registering as an operator to the AVS.
**Step 3**: Adding a easy-to-use CLI command to let anyone register the operator on their behalf with a valid signature.
**Step 4**: Guide for operator, staker, and ISM deployers to on how to utilize the AVS.

For more details, refer to the Hyperlane Improvement Proposal (HIP) 8 here: https://github.com/hyperlane-xyz/hips/blob/kunal/el/HIP-8.md

```[tasklist]
### Contract work
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3589
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3590
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3591
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3592
```

```[tasklist]
### Operators/Agent work
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3594
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3598
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3601
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3600
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3758
```

```[tasklist]
### Execute forge deployment
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3597
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3599
```

```[tasklist]
### Audit
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3735
```

**Comment by avious00** [comment]
@aroralanuk just a heads up, clarified that it's not CLI deployment tooling, so I renamed it to execute forge deployment
