### ISSUE TITLE
Update HIP-8 to reflect design: add diagrams for contract interactions

### ISSUE THREAD

**Issue by aroralanuk** [hyperlane-xyz/hyperlane-monorepo#3589]
Adding diagrams for the following interactions:

- [x] Registering an operator
- [x] Deregistering an operator
- [x] Depositing as a staker
- [ ] Withdrawing as a staker
- [x] Slashing an operator

Lives here: https://github.com/hyperlane-xyz/hips/blob/kunal/el/HIP-8.md but should be moved to el/README.md
```[tasklist]
### Tasks
- [ ] Add to `protocol/ISM/modular-security` docs
```

**Comment by aroralanuk** [comment]
Done as part of docs
