### ISSUE TITLE
Epic: Cross-chain transfer and swap middlewares

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#3626]
This epic captures work to support cross-chain transfer and swap middlewares.

```[tasklist]
### Tasks
- [ ] CosmWasm equivalent as https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3525
- [ ] Test/Upgrade Neutron Mailbox to latest cw-hyperlane
- [ ] Test/Upgrade Injective and Nexus warp routes to allow for self-relaying
```
