### ISSUE TITLE
Epic: Relayer throughput - longer term

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3664]
Longer term issues related to throughput. The first pass of this is tracked here https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3570

Full context here: https://www.notion.so/hyperlanexyz/Improving-Relayer-Throughput-43462a3f52d547458e55d9c66ac93e2f

```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3629
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3572
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3631
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3632
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3634
- [ ] Pipeline `submit`s in the Serial Submitter
```
