### ISSUE TITLE
Epic: CLI/SDK Test Coverage

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#3679]
Goal: increase test coverage (fork, unit, E2E) + investigate speeding up CI times (agent image likely a bottleneck)

```[tasklist]
### Active Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3299
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3446
- [ ] Scope out where to increase test coverage
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3982
- [ ] Investigate speeding up CI times 
```

```[tasklist]
### Related Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1840
- [ ] https://github.com/hyperlane-xyz/issues/issues/657
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3355
```
