### ISSUE TITLE
Set `HYP_KEY` in `hyperlane chain init` along with interactive RPC

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#3724]
```[tasklist]
### Tasks
- [ ] chain id/domain id should be derived from RPC URL
- [ ] interactively prompt (somehow censor in the terminal?) for key flag and instead of writing to config on disk, set in environment
- [ ] domain id should default to chain id but still be configurable
```
