### ISSUE TITLE
Epic: CI coverage + docs for Hybrid PI

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#3734]
```[tasklist]
### Docs
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3581
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3721
- [ ] Bytecode checking in CLI for verifying registry merge
- [ ] Collision checks when adding to registry: chain names, chain ids, and domain ids
```

```[tasklist]
### CI Coverage
- [ ] Core deploy w/warp config
```

**Comment by avious00** [comment]
@yorhodes to update this pending Fri DX conversation
