### ISSUE TITLE
[TxS][SDK] Implement ICA Interface Refactor + Zod Validation

### ISSUE THREAD

**Issue by nbayindirli** [hyperlane-xyz/hyperlane-monorepo#3786]
- Refactor ICA class to destruct function props for use by submitters
- Remove unused chain from `EV5ImpersonatedAccountTxSubmitterProps`
- stopImpersonatingAccount after txs are submitted to `EV5ImpersonatedAccountTxSubmitter`
- Implement Zod validation on `ProposedTransactions` for submitters/transformers
- Implement Zod validation on Submitter/Transformer types
```[tasklist]
### Tasks
- [x] Refactor ICA class to destruct function props for use by submitters
- [x] Remove unused chain from EV5ImpersonatedAccountTxSubmitterProps
- [x] stopImpersonatingAccount after txs are submitted to EV5ImpersonatedAccountTxSubmitter
- [x] Implement Zod validation on ProposedTransactions for submitters/transformers
```

**Comment by nbayindirli** [comment]
Fixed by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3792
