### ISSUE TITLE
feat(cli): default CLI-4.0 E2E testing

### ISSUE THREAD

**Issue by cmcewen** [hyperlane-xyz/hyperlane-monorepo#3982]
```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3994
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3995
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3996
```
