### ISSUE TITLE
Epic: HaaS improvements

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#4234]
```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4227
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4228
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4229
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4230
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4231
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4232
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4233
```
