### ISSUE TITLE
Epic: Solana scraper support

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#4271]
Note: sequencing-wise, it may make sense to coordinate with https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3329 for many things including shipping this

```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3331
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4272
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4301
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4273
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4274
```
