### ISSUE TITLE
Use QuorumProvider / FallbackProvider in ts/rs

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#867]
- [x] https://github.com/abacus-network/abacus-monorepo/issues/868
- [x] https://github.com/abacus-network/abacus-monorepo/issues/869
- [x] https://github.com/abacus-network/abacus-monorepo/issues/870
- [x] https://github.com/abacus-network/abacus-monorepo/issues/871
- [ ] https://github.com/abacus-network/abacus-monorepo/issues/872
- [x] https://github.com/abacus-network/abacus-monorepo/issues/873
- [ ] #875 
- [ ] #874
